#pragma once

#define	WM_SET_THRESHOLD	WM_USER+1
#define	WM_BINARY_MODE		WM_USER+2
#define	WM_ZOOM_IN			WM_USER+3
#define	WM_ZOOM_OUT			WM_USER+4
#define	WM_ZOOM_FIT			WM_USER+5

#define WM_DRW_DEL			WM_USER+6
#define WM_DRW_UPD			WM_USER+7
#define WM_DRW_CUR			WM_USER+8
#define WM_DRW_LINE			WM_USER+9
#define WM_DRW_RECT			WM_USER+10
#define WM_DRW_TRACK_RECT	WM_USER+11
#define WM_DRW_STR			WM_USER+12

#define WM_UPDATE_IMG		WM_USER+13
#define WM_RESTORE_IMG		WM_USER+14

#define WM_UPD_STATUSBAR	WM_USER+15
#define WM_DRW_STRING		WM_USER+16

#define WM_CUR_DEL			WM_USER+17
#define WM_LINE_DEL			WM_USER+18

#define WM_STR_DEL			WM_USER+19
#define WM_RECT_DEL			WM_USER+20


#define WM_DRW_TRACK_CROSS	WM_USER+21
#define WM_DRW_CIRCLE		WM_USER+22
#define WM_CIRCLE_DEL		WM_USER+23

#define WM_SETSCROLLSIZE	WM_USER+24

#define WM_PANE_CLOSED      WM_USER+25
#define WM_PUSH_IMAGEBUF    WM_USER+26

#define WM_IMG_ROT_CW		WM_USER+27
#define WM_IMG_ROT_CCW		WM_USER+28

#define WM_SET_INSPSTATUS	WM_USER+29

#define WM_SET_BINARYMODE	WM_USER+30

#define WM_RIBBON_REMOVECATEGORY	WM_USER+31
#define WM_SET_GRAYPALLETTE			WM_USER+32
#define WM_VISION_PANE_CLOSED		WM_USER+33
#define WM_PANE_NEW_GROUP			WM_USER+34